Remove ros console header and add mandatory hearders
isri-aist/BaselineFootstepPlanner pull request #5
Opened 2024-09-06 05:56 UTC by ThomasDuvinage

As ROS2 is not using the same headers as ROS1, ros/console must be drop. Furthermore, this one is already included in include/BaselineFootstepPlanner/console.h. 

Concerning the other headers, they are needed to compile.

2024-09-06 06:04 UTC, mmurooka requested changes

2024-09-06 06:04 UTC, mmurooka commented on src/FootstepState.cpp
> +#include <math.h>
Is this include necessary? If so, please include cmath instead of math.h.

2024-09-06 06:10 UTC, ThomasDuvinage commented on src/FootstepState.cpp
> +#include <math.h>
yes this header is necessary otherwise std::sqrt is not defined.

2025-03-04 08:36 UTC, mmurooka approved these changes

2025-03-04 08:36 UTC, merged